"""
Named world configurations and mission descriptions.

Each world entry defines the FieldSampler operator config that is
*hidden* from the agent, plus a mission string that is shown to it.
"""

from scienceagent.executor import SimulationExecutor, CircleExecutor, SpeciesExecutor

_GENERAL_FORM = r"$\dfrac{\partial^n \varphi}{\partial t^n} = L[\varphi] + S(\mathrm{particles})$"

_TRUE_LAW_GRAVITY = (
    _GENERAL_FORM + "\n\n"
    r"$n = 0$" + "\n"
    r"$L[\varphi] = \nabla^2\varphi$" + "\n"
    r"$\mathbf{F} = -\nabla\varphi\,/\,p_2$"
)

_TRUE_LAW_YUKAWA = (
    _GENERAL_FORM + "\n\n"
    r"$n = 0$" + "\n"
    r"$L[\varphi] = \nabla^2\varphi - \lambda^{-2}\varphi,\quad \lambda = 2$" + "\n"
    r"$\mathbf{F} = -\nabla\varphi\,/\,p_2$"
)

_TRUE_LAW_FRACTIONAL = (
    _GENERAL_FORM + "\n\n"
    r"$n = 0$" + "\n"
    r"$L[\varphi] = -(-\nabla^2)^{\alpha}\varphi,\quad \alpha = 0.75$" + "\n"
    r"$\mathbf{F} = -\nabla\varphi\,/\,p_2$"
)

_TRUE_LAW_DIFFUSION = (
    _GENERAL_FORM + "\n\n"
    r"$n = 1$" + "\n"
    r"$L[\varphi] = D\,\nabla^2\varphi,\quad D = 0.5$" + "\n"
    r"$\mathbf{F} = -\nabla\varphi\,/\,p_2$"
)

_TRUE_LAW_SPECIES = (
    _GENERAL_FORM + "\n\n"
    r"$n = 0$" + "\n"
    r"$L[\varphi] = \nabla^2\varphi$" + "\n"
    r"$\mathbf{F}_i = -\nabla\varphi_i$" + "\n"
    r"$\text{source\_coupling}_i = 1.0\;\text{(particles 0,1,2)},\; 3.0\;\text{(particles 3,4,5)}$"
)

_TRUE_LAW_CIRCLE = (
    _GENERAL_FORM + "\n\n"
    r"$n = 0$" + "\n"
    r"$L[\varphi] = -(-\nabla^2)^{\alpha}\varphi,\quad \alpha = 0.75$" + "\n"
    r"$\mathbf{F}_i = -\nabla\varphi_i$" + "\n"
    r"$\text{11 particles: 1 center} + \text{10 ring}$"
)

_TRUE_LAW_WAVE = (
    _GENERAL_FORM + "\n\n"
    r"$n = 2$" + "\n"
    r"$L[\varphi] = c^2\nabla^2\varphi,\quad c = 1$" + "\n"
    r"$\mathbf{F} = -\nabla\varphi\,/\,p_2$"
)

WORLDS = {
    "gravity": {
        "description": "Classic inverse-square-law-like attraction mediated by a 2D Laplacian field.",
        "mission": (
            "Two particles interact through an unknown field in a 2D universe. "
            "The field is generated by particle 1 and exerts a force on particle 2. "
            "Discover the law of motion governing particle 2."
        ),
        "executor_kwargs": {
            "operators": [{"type": "laplacian", "params": {"strength": 1.0}}],
            "temporal_order": 0,
        },
        "true_law": _TRUE_LAW_GRAVITY,
        "true_law_title": "True Laplacian",
    },
    "yukawa": {
        "description": "Screened (Yukawa) potential — exponentially suppressed at long range.",
        "mission": (
            "Two particles interact in a universe where forces may be screened at long distances. "
            "Discover the force law, including any distance-dependent suppression."
        ),
        "executor_kwargs": {
            "operators": [{"type": "screening", "params": {"strength": 1.0, "screening_length": 2.0}}],
            "temporal_order": 0,
        },
        "true_law": _TRUE_LAW_YUKAWA,
        "true_law_title": "True Yukawa",
    },
    "fractional": {
        "description": "Fractional Laplacian — anomalous power-law force.",
        "mission": (
            "Two particles interact through a field obeying an unusual spatial operator. "
            "The force may scale with distance in an unexpected way. "
            "Discover the law of motion."
        ),
        "executor_kwargs": {
            "operators": [{"type": "fractional_laplacian", "params": {"strength": 1.0, "alpha": 0.5}}],
            "temporal_order": 0,
        },
        "true_law": _TRUE_LAW_FRACTIONAL,
        "true_law_title": "True Fractional Laplacian",
    },
    "diffusion": {
        "description": "Diffusive (n=1) field — force from a time-dependent spreading field.",
        "mission": (
            "The field in this universe evolves over time by diffusion before exerting forces. "
            "Discover how particle 2 moves in the presence of particle 1."
        ),
        "executor_kwargs": {
            "operators": [{"type": "laplacian", "params": {"strength": 0.5}}],
            "temporal_order": 1,
        },
        "true_law": _TRUE_LAW_DIFFUSION,
        "true_law_title": "True Diffusion",
    },
    "wave": {
        "description": "Wave (n=2) field — oscillatory, retarded forces.",
        "mission": (
            "The field propagates as a wave in this universe. "
            "Forces on particle 2 may depend on the history of the field. "
            "Discover the law of motion."
        ),
        "executor_kwargs": {
            "operators": [{"type": "laplacian", "params": {"strength": 1.0}}],
            "temporal_order": 2,
        },
        "true_law": _TRUE_LAW_WAVE,
        "true_law_title": "True Wave Equation",
    },
    "species": {
        "description": "Standard Laplacian with 6 particles of 2 hidden species (different source strengths).",
        "mission": (
            "You are observing a system of 6 particles in a 2D universe. "
            "All particles interact through an unknown field. "
            "The particles may not all be identical — some may generate "
            "stronger or weaker fields than others. "
            "Your goal is to discover the law of motion governing all particles, "
            "including any differences between them."
        ),
        "executor_class": "SpeciesExecutor",
        "executor_kwargs": {},
        "true_law": _TRUE_LAW_SPECIES,
        "true_law_title": "True Laplacian (two species)",
        "system_prompt": "PhysicsSchool/prompts/run_experiments_species.md",
        "law_stub": (
            "def discovered_law(positions, velocities, duration):\n"
            "    # positions: list of 6 [x, y] coords relative to center\n"
            "    # velocities: list of 6 [vx, vy]\n"
            "    # duration: float, simulate from t=0 to t=duration\n"
            "    # return: list of 6 [x, y] final positions\n"
            "    return final_positions\n"
        ),
        "experiment_format": (
            "<run_experiment>[{\"positions\": "
            "[[0,0],[3,0],[-3,0],[0,3],[0,-3],[4,4]], "
            "\"velocities\": "
            "[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]], "
            "\"measurement_times\": [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]}]"
            "</run_experiment>"
        ),
    },
    "circle": {
        "description": "Fractional Laplacian (alpha=0.75) — 11 particles, 1 center + 10 ring.",
        "mission": (
            "You are observing a system of 11 particles in a 2D universe. "
            "One particle sits at the center; 10 others are arranged on a ring around it. "
            "All particles interact through an unknown field. "
            "Your goal is to discover the law of motion governing all particles."
        ),
        "executor_class": "CircleExecutor",
        "executor_kwargs": {},
        "true_law": _TRUE_LAW_CIRCLE,
        "true_law_title": "True Fractional Laplacian (circle)",
        "system_prompt": "PhysicsSchool/prompts/run_experiments_circle.md",
        "law_stub": (
            "def discovered_law(positions, velocities, duration):\n"
            "    # positions: list of 11 [x, y] coords relative to center\n"
            "    # velocities: list of 11 [vx, vy]\n"
            "    # duration: float, simulate from t=0 to t=duration\n"
            "    # return: list of 11 [x, y] final positions\n"
            "    return final_positions\n"
        ),
        "experiment_format": (
            "<run_experiment>[{\"ring_radius\": 5.0, "
            "\"initial_tangential_velocity\": 0.0, "
            "\"measurement_times\": [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]}]"
            "</run_experiment>"
        ),
    },
}


def get_world(name: str, **executor_overrides) -> dict:
    """
    Return a config dict for the named world with keys:
        executor, mission, true_law, true_law_title,
        system_prompt (path string), law_stub (function signature string)
    """
    if name not in WORLDS:
        raise ValueError(f"Unknown world '{name}'. Available: {list(WORLDS)}")

    entry = WORLDS[name]
    kwargs = {**entry["executor_kwargs"], **executor_overrides}

    executor_class_name = entry.get("executor_class", "SimulationExecutor")
    executor_classes = {
        "SimulationExecutor": SimulationExecutor,
        "CircleExecutor": CircleExecutor,
        "SpeciesExecutor": SpeciesExecutor,
    }
    executor = executor_classes[executor_class_name](**kwargs)

    default_law_stub = (
        "def discovered_law(pos1, pos2, p1, p2, velocity2, duration):\n"
        "    # your best implementation\n"
        "    return final_pos2, final_vel2\n"
    )
    default_system_prompt = "PhysicsSchool/prompts/run_experiments.md"
    default_experiment_format = (
        "<run_experiment>[{\"p1\": 1.0, \"p2\": 1.0, \"pos2\": [3.0, 0.0], "
        "\"velocity2\": [0.0, 0.0], \"measurement_times\": [0.5, 1.0, 2.0]}]</run_experiment>"
    )

    return {
        "executor": executor,
        "mission": entry["mission"],
        "true_law": entry["true_law"],
        "true_law_title": entry["true_law_title"],
        "system_prompt": entry.get("system_prompt", default_system_prompt),
        "law_stub": entry.get("law_stub", default_law_stub),
        "experiment_format": entry.get("experiment_format", default_experiment_format),
    }
